name: Java CI

on:
  push:
    branches: [ "dev"  ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: chmod
      run: sudo chmod 777 -R ./
      
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'


    - name: Build with gradle
      run: ./gradlew shadowJar

    - uses: actions/upload-artifact@v3
      with:
        name: upload build file
        path: ./build/libs